#!/usr/bin/env python3

from rich import print
from rich.prompt import Prompt
import os

OPTIONS = [
    [
        "1. Generate JSON Files",
        [
            "cd data/ramayan/",
            "python3 get_json.py",
        ],
    ],
    [
        "2. Generate JSON Files + Excel zip",
        [
            "rm -f rAmAyaNam.zip",
            "cd data/ramayan/",
            "python3 get_json.py",
            "npx tsx make_excel_files.ts",
            "cp zipped/rAmAyaNam.zip ../../",
        ],
        "[bold]The zip file has been generated as 'rAmAyaNam.zip'[/]",
    ],
    [
        "3. Run Checks on JSON Files",
        [
            "cd data/ramayan/",
            "python3 run_tests.py",
        ],
        "[bold]The test report has been generated as 'data/ramayan/test_output.md'. Open that file and press `[yellow]Ctrl+Shift+V[/]` to view the report[/]",
    ],
    ["4. Launch the web app", ["pnpm dev"]],
]


def main():
    print("[bold yellow]Select an option to run:[/]")
    for option in OPTIONS:
        print(f"[blue]{option[0]}[/]")

    choice = Prompt.ask(
        "Choose an option", choices=[str(i + 1) for i in range(len(OPTIONS))]
    )

    command_info = OPTIONS[int(choice) - 1]
    command = " && ".join(command_info[1])
    os.system(command)
    if len(command_info) == 3:
        print(command_info[2])


if __name__ == "__main__":
    main()
